### ISSUE TITLE
feature: ticker API

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#27]
24h low, 24h high, current price(price of last trade), 24h price change percent, 24h amout, 24h quote amount

similar to kline api

the tricky difference of this API and kline api is, if now is 15:00, ticker API aggregates data from 15:00 yesterday to now, while kline API cares 0:00 UTC yesterday to 0:00 UTC today, 0:00 UTC today to now. The bucket/window is not same.

req:

/restapi/ticker_24h/ETH_USDT

resp example:

```
{
  "market": "ETH_USDT",
  "price_change_percent": "1.96%",
  "last": "1234.56",
  "high": "1300",
  "low": "1200",
  "volume": "8913.30000000",
  "quote_volume": "15.30000000",
  "from": 16xxxx,  // unix timestamp 24h ago
  "to": 16xxx, // now
}
```

**Comment by noel2004** [comment]
So it is supposed to respond a single candlestick item like:

``` json
{
   "s": "ok",
   "t": 1386493512,
   "c": 42.1,
   "h": 43.0,
   "l": 40.4,
   "v":12000
}
```
(no open price because it make no sense) ?

I think the req is bare (without any parameters, maybe an optional for specifying another time, rather than now) . How fast should the api update its response? Is one minute acceptable? or even less (like every 30s or 10s or even 1s) 

Not sure we should use some tricks to trying to reduce the calculations in aggregations (like caching the aggregation results for each hours). Modern db often has enough tricks inside its querying to cache and reuse part of the results and we may be not bother to waste time on that.

**Comment by lispc** [comment]
no open price because it make no sense ?:       price change percent is needed. So either percent, or price 24h before.   
maybe an optional for specifying another time: don't need.   
Is one minute acceptable?:  5s seems better. But if it hurts performance or make implementation too complex, i think 1min is ok for a while.      
may be not bother to waste time on that: ok
