### ISSUE TITLE
Deps: migrate to sqlx from diesel

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#6]
From my personal experience, Diesel is quite hard to use when handling complex SQL... 

Here:

<https://github.com/lispc/viabtc-exchange-rust/commit/915babf64d5fbd337f35dd881922a30753925701#diff-efc588f9ca952d72e6bfef2034a97d539bc8b757e6e458dabfb8137da79af07dR63-R83>

And here:

<https://github.com/Fluidex/dingir-exchange/blob/1233e3a202b30b9a3623368ec233fdc5c54cda17/src/database.rs#L59>

I remember I spent much time on those codes ...

Sqlx is becoming more and more mature and seems less type-safe on ORM and more flexiable for complex raw sqls ( timescaledb sql ? maybe)  , and more friendly to async . 

migration examples: 
<https://git.2x.ax/~saiko/modsite/commit/cd733e953863c9c20ffb288355fc045d6dcc983e>.   
<https://github.com/matter-labs/zksync/commit/fe608965ea91d4774bde1546d2196ea41d81960a>

<del>Other methods are </del>

<del>1. use <https://github.com/mehcode/tokio-diesel/blob/master/examples/simple.rs> as a temporary solution 
2. use diesel only as a sql builder, then execute sql using sqlx. This method needs less modification...</del>

**Comment by noel2004** [comment]
The codes currently involving diesel (in database.rs, persist.rs controller.rs etc.) will be replaced by the new implement base on sqlx. So do the table definitions and migrations.

**Comment by noel2004** [comment]
https://github.com/noel2004/dingir-exchange/commit/3d990b98790d9263bbd11f48f49a62a172a4385b

Now this WIP commit provide a migration to sqlx in an as-is way.

The most difficult part (inserting operation) has done, though still not so grace.

Now following are left:

+ migrate the rest part and abandon diesel: turning the whole framework into async may take times, and the current code will definitely ruin because of the many unsafe accessing to controllers, especially for the debug features. I have some idea to resolve the issue (induce a "Stop the world" feature in debug, which always imply a single-thread model)
+ migration (I am not so sure how the file should be organized and naming, lacking docs, may spend some time. It seems we should put up and down in separated path)
+ some unit tests (maybe it is a good idea to apply sqlx's compling-time verification under some special cfg flag?)

Now I feel lucky to put the dead-line late ...

**Comment by noel2004** [comment]
One more question is batching: there is still no feature in sqlx to achieve batching inserting for a vec<T> like diesel. It require quite a work to transform the whole structure, like `Vec<A> -> A'{ a: Vec<i32>} for a struct A{a: i32} `. It would be a macro-work, hard!

**Comment by lispc** [comment]
Done
